"""add total_price column to transactions

Revision ID: 8f79e5ca736e
Revises: 581aed6fa39c
Create Date: 2025-10-26 17:08:58.326343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f79e5ca736e'
down_revision: Union[str, Sequence[str], None] = '581aed6fa39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'total_price')
    # ### end Alembic commands ###
