"""add supplier.created_at

Revision ID: c8267f598c7b
Revises: 4d07bd3ae63b
Create Date: 2025-11-29 18:44:09.126992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8267f598c7b'
down_revision: Union[str, Sequence[str], None] = 'ffdeabc8e86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    # ### end Alembic commands ###
    """Upgrade schema (safe/idempotent)."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # add suppliers.created_at only if missing
    cols = [c["name"] for c in inspector.get_columns("suppliers")]
    if "created_at" not in cols:
        op.add_column(
            "suppliers",
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        )
    # if you intended to make products.quantity NOT NULL, do that carefully and only if column exists
    prod_cols = [c["name"] for c in inspector.get_columns("products")]
    if "quantity" in prod_cols:
        op.alter_column("products", "quantity", existing_type=sa.INTEGER(), nullable=False)
    # do NOT drop transaction.product_id or create a FK to products.name here — keep changes minimal
    # leave transaction.total_price and users.role untouched here
    #  end safe changes
    # end Alembic commands


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
      # ### end Alembic commands ###
    """Downgrade schema (revert only safe changes)."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = [c["name"] for c in inspector.get_columns("suppliers")]
    if "created_at" in cols:
        op.drop_column("suppliers", "created_at")
    prod_cols = [c["name"] for c in inspector.get_columns("products")]
    if "quantity" in prod_cols:
        op.alter_column("products", "quantity", existing_type=sa.INTEGER(), nullable=True)
    # do NOT re-create or drop transaction.product_id here
# ...existing code...
