"""add stock market table

Revision ID: e7ee74f25705
Revises: c1b7cab0fcd5
Create Date: 2026-02-22 23:36:19.500425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ee74f25705'
down_revision: Union[str, Sequence[str], None] = 'c1b7cab0fcd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure unique constraints exist on referenced columns before creating foreign keys
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    # Create the stock_movement table with foreign keys to unique columns
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_name'], ['products.name'], ),
    sa.ForeignKeyConstraint(['user_name'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movement_id'), 'stock_movement', ['id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'products', ['product_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_products_name'), 'products', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_stock_movement_id'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_constraint('uq_products_name', 'products', type_='unique')
    # ### end Alembic commands ###
