"""fix users role and employees

Revision ID: ecb72c2f9118
Revises: 846c2871d2f1
Create Date: 2026-02-21 23:13:56.708714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb72c2f9118'
down_revision: Union[str, Sequence[str], None] = '846c2871d2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    # ### end Alembic commands ###
